### ISSUE TITLE
Demo is not responsive..

### ISSUE THREAD

**Issue by lukejacksonn** [vladocar/SMART-CSS-GRID#1]
Am I missing something here?

![css](https://user-images.githubusercontent.com/1457604/39521786-def8e27e-4e07-11e8-9185-ee3b9dccf5b7.gif)

**Comment by vladocar** [comment]
Yes it is Safari window doesn't resize to 480px.. You can  change 480px in the CSS or try different browser for testing.

**Comment by lukejacksonn** [comment]
This was in chrome. The fact that you get any page overflow really doesn't scream _responsive_; at best this behaves as _adaptive_. I am not trying to be pedantic or saying that the project is bad but if this is truly a "responsive smart grid" then the demo is not doing it any justice. Like I said, perhaps I am missing something.

**Comment by vladocar** [comment]
This is how I view the demo in Chrome Version 66.

![screencapture-vladocar-github-io-smart-css-grid-2018-05-02-15_55_27](https://user-images.githubusercontent.com/34764/39527394-9e4a924e-4e21-11e8-875e-fb2c5051ef5f.png)

**Comment by lukejacksonn** [comment]
This is not a browser issue.. it behaves the same in chrome and safari (and probably edge). The problem is this is **not** a "fluid responsive layout system". Perhaps that is not what you were going for, but it is what you are claiming that this is.

![rwd-vs-adapt-example](https://user-images.githubusercontent.com/1457604/39529858-937583ee-4e1f-11e8-811e-8f296cec8953.gif)

The above gif demonstrates the difference between _responsive_ (on top) and _adaptive_ (on bottom) taken from [here](https://css-tricks.com/the-difference-between-responsive-and-adaptive-design). There is another good article [here](http://blog.froont.com/9-basic-principles-of-responsive-web-design/) but I feel like I am being pedantic now so I will leave you to it. If this works for people then that is great!

![01_responsive-vs-adaptive](https://user-images.githubusercontent.com/1457604/39530203-5f894182-4e20-11e8-8ee8-8d1f5129d407.gif)

![02_relative-units-vs-static-units-1](https://user-images.githubusercontent.com/1457604/39530211-630d3994-4e20-11e8-9ac0-18848350c7fe.gif)

**Comment by lukejacksonn** [comment]
Good idea 👍 that would demonstrate it better!

**Comment by badcat** [comment]
Hmm - wouldn't simply changing the .main class from width: 960px; to max-width: 960px; suffice for the demo?

**Comment by vladocar** [comment]
@badcat Yes, absolutely. That will work. But I don't want 960px to be the standard I hope people will understand they can change this number into any value or unit. That is the best feature of this project any size or unit will work.
