### ISSUE TITLE
IE not support

### ISSUE THREAD

**Issue by mrronalz** [vladocar/SMART-CSS-GRID#6]
I try to use smart-css-grid but ie not work. It would be good if it support IE. Thanks!

**Comment by vladocar** [comment]
Can work in IE with -ms- prefix. https://caniuse.com/#feat=css-grid

**Comment by mrronalz** [comment]
I try to use -ms-prefix but it still now work.

**Comment by vladocar** [comment]
In order to work you need to make some serious changes to the code.. at this point is better to use flexbox. Take a look into my other project Flex Katana: https://vladocar.github.io/Katana/ it works in IE10
